export enum ProductDetailsText {
  PRODUCT_1_TITLE = "Blue Top",
  PRODUCT1_PARAGRAPH = "Category: Women > Tops",
  ADD_TO_CART = "Add to cart",
  IN_STOCK = "In Stock",
  NEW = "New",
  POLO = "Polo",
  WRITE_YOUR_REVIEW = "Write Your Review",
  RS_500 = "Rs. 500",
  YOUR_NAME = "Your Name",
  EMAIL_ADDRESS = "Email Address",
  ADD_REVIEW = "Add Review Here!",
  BRAND = "Brand",
  CONDITION = "Condition",
  AVAILABILITY = "Availability",
  LINK = "product_details",
}
