export type EnvVars = {
  AUTOMATION_USER: string;
  AUTOMATION_BASEURL: string;
  AUTOMATION_PASSWORD: string;
  AUTOMATION_USER_CORRECT: string;
  AUTOMATION_PASSWORD_CORRECT: string;
  AUTOMATION_USER_INCORRECT: string;
  AUTOMATION_PASSWORD_INCORRECT: string;
};
